name: Smart
on:
  push:
    branches:
      - main
jobs:
  Hello_word_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
        
      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-docker-app:latest .  

      # Step 4: Run Docker container
      - name: Run Docker container
        run: |
          docker run --name my-running-app -d my-docker-app:latest

      # Optional Step 5: Check logs to confirm entrypoint execution
      - name: Check logs
        run: |
          docker logs my-running-app
          
      # Optional Step 6: Cleanup
      - name: Cleanup
        run: |
          docker rm -f my-running-app || true
