name: Smart
on:
  push:
    branches:
      - main
jobs:
  Hello_word_job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: My Docker Build Action_181992
        uses: Praveen-1992/my-docker-app@v5
     # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
        
       # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t my-docker-app:latest .  

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker tag my-docker-app:latest ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest 

      # Step 6: Run the Docker image
      - name: Run Docker container
        run: |
          docker run -d --name my-running-app ${{ secrets.DOCKER_USERNAME }}/my-docker-app:latest     
     
      
